### PR TITLE
fix(sidebar): nav link target doesn't work through appHtmlAttr

### PR DESCRIPTION
**Pull request by Hagith**

### CODE REVIEW

**Comment by xidedix** [comment]
Hi @Hagith 
Thanks for the heads-up and PR.
We'll investigate the issue.

**Comment by xidedix** [comment]
The router swaps components in the router-outlet existing within the running application. It's not shared across multiple windows. Retargeting a  link into another window requires re-bootstrapping of the entire application. The same can be achieved using a html link.

**Comment by Hagith** [comment]
Yes, your'e right. But it's bit difficult to force coreui to render html link (`*ngSwitchCase="'external'"`). This is automatically computed in `isExternalLink()` as `this.item.url.substring(0, 4) === 'http'`.
This forces to build full URL with current protocol, domain and `baseHref` configured in `angular.json`.
What about extending `isExternalLink()` to: 
`this.item.url.substring(0, 4) === 'http' || (this.item.attributes && this.item.attributes.target)`?

**Comment by Hagith** [comment]
I just checked that extending `isExternalLink()` is not sufficient. It will not take `baseHref` into account, so our "forced" external link will be broken.

**Comment by Hagith** [comment]
> * The `target` attribute for an external link works as expected. There is no need to add line 6.

Your'e right, removed.

**Pull request merged**
